name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.13.5]
        poetry-version: [2.1.3]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry ${{ matrix.poetry-version }}
        run: |
          pip install "poetry==${{ matrix.poetry-version }}"
      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        shell: bash
        run: poetry install --no-root

      - name: Test
        env:
          DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"
          SECRET_KEY: "django-insecure-uma-string-aleatoria-32-caracteres"
        run: |
          poetry run python manage.py test
