name: Python Pull Request Workflow
on: [pull_request]

jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.5
      - name: Install poetry
        run: |
          pip install "poetry==2.1.3"
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Install dependencies
        shell: bash
        run: poetry install --no-root

      - name: Test
        env:
          DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"
          SECRET_KEY: "django-insecure-uma-string-aleatoria-32-caracteres"
        run: |
          poetry run python manage.py test
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.17.0
        continue-on-error: true
        with:
          reporter: github-pr-review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


